Lab03/Lab03/Models/ErrorViewModel.cs
namespace lab3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab03/Lab03/Models/NqtProduct.cs
using Microsoft.AspNetCore.Mvc;

namespace lab3.Models
{
    public class NqtProduct : Controller
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
    }
}

Lab03/Lab03/Controllers/NqtHomeController.cs
using System.Diagnostics;
using lab3.Models;
using Microsoft.AspNetCore.Mvc;

namespace lab3.Controllers
{
    public class NqtHomeController : Controller
    {
        private readonly ILogger<NqtHomeController> _logger;

        public NqtHomeController(ILogger<NqtHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult NqtIndex()
        {
            var products = new List<NqtProduct>
            {
                new NqtProduct { Id = 1, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/product1.jpg" },
                new NqtProduct { Id = 2, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/product1.jpg" },
                new NqtProduct { Id = 3, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/product1.jpg" }
            };
            return View(products);
        }

        public IActionResult NqtAbout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult GetHotProducts()
        {
            // Giả lập dữ liệu (thay bằng truy vấn từ database nếu cần)
            var products = new List<NqtProduct>
        {
            new NqtProduct { Id = 1, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/product1.jpg" },
            new NqtProduct { Id = 2, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/product1.jpg" },
            new NqtProduct { Id = 3, Name = "Nồi cơm điện cao tần Nagakawa NAG0102", Image = "/product1.jpg" }
        };

            return PartialView("_NqtHotProduct", products);
        }
    }
}

Lab03/Lab03/ViewComponents/NqtHotProductViewComponent.cs
using lab3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

public class NqtHotProductViewComponent : ViewComponent
{
    public async Task<IViewComponentResult> InvokeAsync()
    {
        var hotProducts = new List<NqtProduct>
        {
            new NqtProduct { Name = "Nồi cơm điện tử Nagakawa NAG0102", Image = "hotproduct1.jpg" },
            new NqtProduct { Name = "Nồi cơm điện tử Nagakawa NAG0102", Image = "hotproduct2.jpg" },
            new NqtProduct { Name = "Nồi cơm điện tử Nagakawa NAG0102", Image = "hotproduct3.jpg" }
        };
        return View(hotProducts);
    }
}

public class Product
{
    public string Name { get; set; }
    public string Image { get; set; }
}

Lab03/Lab03/Views/NqtHome/NqtAbout.cshtml
@{
    ViewData["Title"] = "Privacy Policy";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

Lab03/Lab03/Views/NqtHome/NqtIndex.cshtml
@model List<NqtProduct>

<h2>Sản phẩm mới nhất</h2>
<div class="row">
    @foreach (var product in Model)
    {
        <div class="col-md-4">
            <img src="~/images/@product.Image" alt="@product.Name" class="img-fluid" />
            <p>@product.Name</p>
        </div>
    }
</div>

@await Component.InvokeAsync("NqtHotProduct")

Lab03/Lab03/Views/NqtHome/_NqtCategoryPartial.cshtml
<h3>Danh mục sản phẩm</h3>
<ul>
    <li><a href="#">Ví dụ</a></li>
    <li><a href="#">Thẻ làng</a></li>
    <li><a href="#">Từ khóa</a></li>
    <li><a href="#">Gợi ý</a></li>
    <li><a href="#">Lọc</a></li>
</ul>